version: '3'
services:
  chat_bot_node:
    container_name: chat_bot_node
    image: node:11
    volumes:
      - ./chat-websocket-server:/app
    working_dir: /app
    build:
      context: .
      dockerfile: ./Dockerfile-chat_bot_node
    command: npm run start 
    environment:
      - PORT=6860
      - MONGO_HOST=chat_bot_mongodb
    tty: true
    ports:
      - 6860:6860
    links:
      - chat_bot_mongodb

  chat_bot_mongodb:
    container_name: chat_bot_mongodb
    image: mongo
    volumes:
      - ./db:/data/db


  chat_replies_api_nginx:
    container_name: chat_replies_api_nginx
    image: nginx:latest
    working_dir: /var/www
    ports:
      - "80:81"
      - "443:443"
    volumes:
      - ./chat-replies-api:/var/www
      - ./chat_replies_api_nginx.conf:/etc/nginx/conf.d/site.conf

  chat_replies_api_phpfpm:
    container_name: chat_replies_api_phpfpm
    image: php:7.2-fpm
    working_dir: /var/www    
    build:
      context: .
      dockerfile: ./Dockerfile-chat_replies_api_phpfpm

    volumes:
      - ./chat-replies-api:/var/www