version: '3'
services:
  chat_bot_node:
    container_name: chat_bot_node
    image: node:11
    volumes:
      - ./:/app
      - /app/node_modules
      - /var/www/kiteprop/storage/framework/sessions:/sessions
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start 
    environment:
      - PORT=6860
      - MONGO_HOST=chat_bot_mongodb
    tty: true
    ports:
      - 6860:6860
    links:
      - chat_bot_mongodb

  chat_bot_mongodb:
    container_name: chat_bot_mongodb
    image: mongo
    volumes:
      - ./db:/data/db